import type { Metadata } from "next";
import { Geist, Geist_Mono, Cherry_Bomb_One, Patrick_Hand } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 🍒 new cute retro font
// const cherry = Cherry_Bomb_One({
//   variable: "--font-cute",
//   subsets: ["latin"],
//   weight: "400",
// });

const patrick = Patrick_Hand({
  variable: "--font-cute",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${patrick.variable} antialiased`}
      >
        <div className="apply-cute">
          {children}
        </div>
        
      </body>
    </html>
  );
}
